// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: catalog/favorites.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Favorites []*Favorite `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
}

func (x *FavoriteList) Reset() {
	*x = FavoriteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalog_favorites_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoriteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteList) ProtoMessage() {}

func (x *FavoriteList) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_favorites_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteList.ProtoReflect.Descriptor instead.
func (*FavoriteList) Descriptor() ([]byte, []int) {
	return file_catalog_favorites_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteList) GetFavorites() []*Favorite {
	if x != nil {
		return x.Favorites
	}
	return nil
}

type Favorite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavoriteId int64  `protobuf:"varint,1,opt,name=favoriteId,proto3" json:"favoriteId,omitempty"`
	CustomerId int64  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Payload    string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Favorite) Reset() {
	*x = Favorite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalog_favorites_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Favorite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorite) ProtoMessage() {}

func (x *Favorite) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_favorites_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorite.ProtoReflect.Descriptor instead.
func (*Favorite) Descriptor() ([]byte, []int) {
	return file_catalog_favorites_proto_rawDescGZIP(), []int{1}
}

func (x *Favorite) GetFavoriteId() int64 {
	if x != nil {
		return x.FavoriteId
	}
	return 0
}

func (x *Favorite) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Favorite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Favorite) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_catalog_favorites_proto protoreflect.FileDescriptor

var file_catalog_favorites_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x22, 0x3f, 0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x12, 0x5a,
	0x10, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_favorites_proto_rawDescOnce sync.Once
	file_catalog_favorites_proto_rawDescData = file_catalog_favorites_proto_rawDesc
)

func file_catalog_favorites_proto_rawDescGZIP() []byte {
	file_catalog_favorites_proto_rawDescOnce.Do(func() {
		file_catalog_favorites_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_favorites_proto_rawDescData)
	})
	return file_catalog_favorites_proto_rawDescData
}

var file_catalog_favorites_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_favorites_proto_goTypes = []any{
	(*FavoriteList)(nil), // 0: catalog.FavoriteList
	(*Favorite)(nil),     // 1: catalog.Favorite
}
var file_catalog_favorites_proto_depIdxs = []int32{
	1, // 0: catalog.FavoriteList.favorites:type_name -> catalog.Favorite
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_favorites_proto_init() }
func file_catalog_favorites_proto_init() {
	if File_catalog_favorites_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_catalog_favorites_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FavoriteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalog_favorites_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Favorite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_favorites_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_favorites_proto_goTypes,
		DependencyIndexes: file_catalog_favorites_proto_depIdxs,
		MessageInfos:      file_catalog_favorites_proto_msgTypes,
	}.Build()
	File_catalog_favorites_proto = out.File
	file_catalog_favorites_proto_rawDesc = nil
	file_catalog_favorites_proto_goTypes = nil
	file_catalog_favorites_proto_depIdxs = nil
}
