// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: authenticate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AusweisService_Summon_FullMethodName = "/ausweis.AusweisService/Summon"
)

// AusweisServiceClient is the client API for AusweisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AusweisServiceClient interface {
	Summon(ctx context.Context, in *SummonRequest, opts ...grpc.CallOption) (*Customer, error)
}

type ausweisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAusweisServiceClient(cc grpc.ClientConnInterface) AusweisServiceClient {
	return &ausweisServiceClient{cc}
}

func (c *ausweisServiceClient) Summon(ctx context.Context, in *SummonRequest, opts ...grpc.CallOption) (*Customer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Customer)
	err := c.cc.Invoke(ctx, AusweisService_Summon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AusweisServiceServer is the server API for AusweisService service.
// All implementations must embed UnimplementedAusweisServiceServer
// for forward compatibility.
type AusweisServiceServer interface {
	Summon(context.Context, *SummonRequest) (*Customer, error)
	mustEmbedUnimplementedAusweisServiceServer()
}

// UnimplementedAusweisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAusweisServiceServer struct{}

func (UnimplementedAusweisServiceServer) Summon(context.Context, *SummonRequest) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Summon not implemented")
}
func (UnimplementedAusweisServiceServer) mustEmbedUnimplementedAusweisServiceServer() {}
func (UnimplementedAusweisServiceServer) testEmbeddedByValue()                        {}

// UnsafeAusweisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AusweisServiceServer will
// result in compilation errors.
type UnsafeAusweisServiceServer interface {
	mustEmbedUnimplementedAusweisServiceServer()
}

func RegisterAusweisServiceServer(s grpc.ServiceRegistrar, srv AusweisServiceServer) {
	// If the following call pancis, it indicates UnimplementedAusweisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AusweisService_ServiceDesc, srv)
}

func _AusweisService_Summon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AusweisServiceServer).Summon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AusweisService_Summon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AusweisServiceServer).Summon(ctx, req.(*SummonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AusweisService_ServiceDesc is the grpc.ServiceDesc for AusweisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AusweisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ausweis.AusweisService",
	HandlerType: (*AusweisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Summon",
			Handler:    _AusweisService_Summon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticate.proto",
}
